# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-24 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=32)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostCount',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('ip', models.TextField(default=0)),
                ('times', models.IntegerField(default=0)),
                ('title', models.TextField()),
                ('pub_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('show', models.SmallIntegerField(default=0)),
                ('title', models.TextField()),
                ('count', models.IntegerField(default=1)),
                ('field', models.TextField()),
            ],
        ),
    ]
