# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-24 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcount',
            name='pub_time',
            field=models.DateTimeField(null=True),
        ),
    ]
