# Generated by Django 2.0.2 on 2018-02-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=False)),
                ('title', models.TextField()),
                ('count', models.IntegerField(default=1)),
                ('field', models.TextField()),
            ],
        ),
    ]
