# Generated by Django 2.0.2 on 2018-02-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='show',
            field=models.SmallIntegerField(default=0),
        ),
    ]
