# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-02 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_auto_20180224_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcount',
            old_name='times',
            new_name='rows',
        ),
    ]
