# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-18 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0003_auto_20180218_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('title', models.TextField()),
            ],
        ),
    ]
