# Generated by Django 2.0.2 on 2018-03-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0003_auto_20180302_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcount',
            name='counts',
            field=models.IntegerField(default=0),
        ),
    ]
