# Generated by Django 2.0.2 on 2018-03-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0004_postcount_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='count',
        ),
        migrations.AddField(
            model_name='table',
            name='expired',
            field=models.IntegerField(default=0),
        ),
    ]
