# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-18 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0004_postcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcount',
            old_name='count',
            new_name='times',
        ),
    ]
